# fly.toml app configuration file generated for elparcheplotter on 2025-09-08T15:23:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elparcheplotter'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
